Bookstore/Components/TypesViewComponent.cs
using System;
using System.Linq;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository bookYo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            bookYo = temp;
        }

        public IViewComponentResult Invoke()
        {
            //ViewBag.SelectedType = RouteData?.Values["category"]; //means can be nullable
            var categories = bookYo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x); //default order

            return View(categories); // pass the query of WHAT will be shown and in what order into the view
        }
    }
}

Bookstore/Views/Shared/BookSummary.cshtml
@{
}
@model Book


<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <span class="badge bg-info" style="float:right">
            @Model.PageCount total pages
        </span>
    </div>

    <ul>
        <li>Book Type: @Model.Category</li>
        <li>Author: @Model.Author</li>
        <li>This book costs $@Model.Price</li>
    </ul>


    <form method="post" asp-page="/Buy">

        <input type="hidden" asp-for="@Model.BookId" />
        @*<input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />*@

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end" style="float:right">Buy</button>
        </span>
    </form>
</div>

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body>

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">Book Store</span>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>


    </div>
</body>
</html>